# this is usable inside Dockerfile.server container
dev:
  roserver: redoctober.local:8080
  ca: /tmp/server.crt
  ro_user: Alice
  ro_password: Lewis
  pgp_keyring_path: /etc/pal/keyrings/secring.gpg
  pgp_passphrase: paltest
  pgp_cipher: aes256
  pgp_hash: sha256
  labels_enabled: true
  labels_retriever: docker
  notary_trust_server: https://notary.docker.io
  notary_trust_dir: .trust
