FROM debian:jessie

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates

COPY ./bin/pald /usr/bin/pald
COPY ./config.yaml /etc/pal/config.yaml
COPY ./testdata/secring.gpg /etc/pal/keyrings/secring.gpg
ADD ./script/pald-integration /docker-entrypoint

VOLUME /var/run

ENTRYPOINT ["/docker-entrypoint"]
CMD ["/usr/bin/pald", \
    "-addr=unix:///var/run/pald.sock", \
    "-config=/etc/pal/config.yaml", \
    "-env=dev"]
