# This dockerfile is used for integration test and is not a recommended way to
# run pal client. Refer to docker-compose.yml on how this image is run.
FROM debian:jessie

LABEL pal.labels=pal

RUN apt-get update && apt-get install -y --no-install-recommends \
      netcat \
      jq \
      curl \
      ca-certificates
