#!/bin/bash -e
docker-compose build
docker-compose up --abort-on-container-exit
docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | while read code; do  
  if [ "$code" == "1" ]; then    
    exit 1
  fi
done
